### ISSUE TITLE
Improvements

### ISSUE THREAD

**Issue by migueldelmazo** [Adalab/m1-evaluacion-intermedia-luzagm#1]
Really cool job @luzagm !!!

Here you have some tips to improve the exercise:

## HTML
- [x] Fix the language of the page

## CSS - selectors
- [x] Class selectors are free, let's use them instead tag selectors (ul > li > a)
- [x] Logo shold not be inside nav

## CSS - box model
- [x] Header should be fixed to top of the page.
- [x] Block elements like our main one do not need a width: 100% or width: 100vw property to tell them to do what they are going to do anyway ;)
- [x] Your `main` element has some top padding, that's a solution to prevent the main title to disappear behind the fixed header but consider using min-height to do the trick ;)

## CSS - flex
- [x] Try to use flex instead of absolute positions to make tablet version of the header

## CSS - other
- [x] Avoid uppercase/capital on HTML texts, and `br` tag we can transform the text with CSS; this way we keep concepts separated, HTML for content, and CSS for styles
- [x] Finish the main title styles: words should jump and the typography is bolder without strong

## Assets
- [x] Use relative routes like `./styles/main.css`.

## Good practices
- [x] Indent and avoid extra white spaces to improve readability and avoid bugs
- [x] Try to improve your commit messages, better in English and using imperative
- [x] Try to use imperative for your commit messages. Ex. - > Fix central text
- [x]  Do not repeat flex-direction in media queries https://github.com/Adalab/m1-evaluacion-intermedia-luzagm/blob/master/styles/style.css#L61
- [x] Fix main area height

## Final remarks

Once you have these fixed try to finish the styles.
Start with the header and go step by step:

- add behavior styles: fix it to the window
- add structural styles: reset browser styles, center content (use whatever you feel more comfortable with: flex, text-align, margin auto...), add margin, padding...
- add cosmetic styles: color, background color...

Then repeat the same with main content.

Let me know if you have any doubts ;)

Go for it!!

**Comment by migueldelmazo** [comment]
Hay algunas cosas que mejorar pero en general buen trabajo 

![Good job](https://media.giphy.com/media/oGO1MPNUVbbk4/giphy.gif)

**Comment by luzagm** [comment]
¿Dónde podemos ver el enunciado del ejercicio para corregir los errores que me marcas y poner tipografías, mágenes y demás exactos?

**Comment by migueldelmazo** [comment]
Aquí https://github.com/Adalab/m1-evaluacion-intermedia-migueldelmazo !!

**Comment by luzagm** [comment]
Vale, creo que ya lo tengo (lo medio había corregido después del examen...). Sólo tengo un par de dudas respecto a los comentarios que me haces. 

1. No sé muy bien cómo arreglar este punto: "Block elements like our main one do not need a width: 100% or width: 100vw property to tell them to do what they are going to do anyway". Sólo tengo un elemento tipo block, que es el del texto central del ejercicio.
Para que la página tenga todo el color azul si que necesito ponerle heigh 100vh, porque sino simplemente coloreala franja del bloque de texto. ¿Hay alguna otra forma de hacerlo?

2. En las media queries me pides no repetir del flex-direction, pero en versión de móvil le obligué a ponerse en columna, es necesario para que vuelva a fila indicárselo, ¿no?

**Comment by migueldelmazo** [comment]
Hola @luzagm respecto a tu pregunta: 

No sé muy bien cómo arreglar este punto: "Block elements like our main one do not need a width: 100% or width: 100vw property to tell them to do what they are going to do anyway". Sólo tengo un elemento tipo block, que es el del texto central del ejercicio.
Para que la página tenga todo el color azul si que necesito ponerle heigh 100vh, porque sino simplemente coloreala franja del bloque de texto. ¿Hay alguna otra forma de hacerlo?

No sé si lo has arreglado o me he equivocado yo. La idea es que los elementos de bloque como el main ocupan todo el ancho del que disponen y por ello no hacía falta fijarles un ancho al 100% o 100vw que ya por defecto tienen.

**Comment by migueldelmazo** [comment]
Respecto a tu pregunta:

En las media queries me pides no repetir del flex-direction, pero en versión de móvil le obligué a ponerse en columna, es necesario para que vuelva a fila indicárselo, ¿no?

Lo que quiero decir es que `.nav-bar` ya tiene `display: flex` en la línea 8. No hace falta volverlo a poner en dentro de las media queries.

**Comment by migueldelmazo** [comment]
Y en el cambio que pedimos:

Your main element has some top padding, that's a solution to prevent the main title to disappear behind the fixed header but consider using min-height to do the trick ;)

Lo que queremos decir es que si la altura de ventana es muy pequeña el texto principal se pone por detrás de la cabecera, y para evitar eso le ponemos un min-height al main area. Prueba lo que pone en la imagen:

![Captura de pantalla de 2019-07-07 18-40-57](https://user-images.githubusercontent.com/3619686/60771412-21b6dd80-a0e8-11e9-8d66-8c0b2ba70e63.png)

**Comment by migueldelmazo** [comment]
Gracias por hacer las mejoras que os hemos pedido!!!
